package com.evergent.corejava.ExceptionalHandling;

public class ArrayIndexOutOf13 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		int arr[]= {112,3,4,2,4};
		try {
		System.out.println(arr[2]);
		}
		catch(Exception e)
		{
			System.out.println(e);
		}

	}

}
